spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/capita
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      format_sql: true
      globally_quoted_identifiers: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
  sql:
    init:
      mode: always
      continue-on-error: true
